---
title: "cellvel: quantifying cell migration speed with hierarchical Bayesian models"
author: "Simo Kitanovski (simo.kitanovski@uni-due.de)"
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{User Manual: cellvel}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(comment = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
```


# Background

```{r}
library(cellvel)
library(ggplot2)
library(ggforce)
library(patchwork)
ggplot2::theme_set(new = theme_bw(base_size = 10))
```


# Data (raw)

```{r}
data("d_clean", package = "cellvel")
knitr::kable(d[1:10,], row.names = F, digits = 2)
```

```{r, fig.width=6, fig.height=5}
ggplot(data = d)+
  facet_wrap(facets = ~treatment+batch, scales = "free_y")+
  geom_sina(aes(x = as.factor(dose), col = replicate, y= v), size = 0.5)+
  theme_bw()+
  xlab(label = "dose")
```


# Data (scaled)

```{r, fig.width=6, fig.height=4}
ggplot(data = d)+
  facet_wrap(facets = ~treatment+batch, scales = "free_y")+
  geom_sina(aes(x = as.factor(dose), col = replicate, y= v/max(v)), size = 0.5)+
  theme_bw()+
  xlab(label = "dose")+
  ylab(label = "s")
```


# Model

```{r, fig.width=7, fig.height=3.5}
o <- cellvel(x = d,
             model = "M",
             control = list(mcmc_warmup = 300,
                            mcmc_steps = 600,
                            mcmc_chains = 3,
                            mcmc_cores = 1,
                            mcmc_algorithm = "NUTS",
                            adapt_delta = 0.9,
                            max_treedepth = 10))
```


# Treatment:dose specific effects

```{r, fig.width=6, fig.height=3}
ggplot(data = o$s$eff_group_mu)+
  geom_line(aes(x = dose, y = mean, col = treatment))+
  geom_point(aes(x = dose, y = mean, col = treatment))+
  geom_errorbar(aes(x = dose, y = mean, ymin = X2.5., ymax = X97.5., 
                    col = treatment), width = 0.04)
```



# Treatment:dose profiles

```{r, fig.width=10, fig.height=5}
get_profiles(x = o)
```




# Compare effects at specific doses
Huge differences in treatment effects at dose = 2, 3 and 4. At dose = 1 and 
dose = 5, unclear differences in treatment effects.

```{r, fig.width=6, fig.height=4}
u <- get_dose_comparison(x = o)
u$pmax <- round(x = u$pmax, digits = 2)

ggplot(data = u)+
  facet_wrap(facets = ~paste0("dose=", dose))+
  geom_tile(aes(x = treatment_i, y = treatment_j, fill = pmax), col = "white")+
  geom_text(aes(x = treatment_i, y = treatment_j, label = pmax), size = 3, col = "black")+
  scale_fill_distiller(name = expression(pi), palette = "Spectral", limits = c(0, 1))
```




# PPC

```{r, fig.width=6, fig.height=8}
e <- rstan::extract(object = o$f, par = "y_hat_sample")$y_hat_sample
e <- reshape2::melt(data = e)
colnames(e) <- c("iter", "s", "yhat")
q <- o$x[, c("s", "treatment", "dose", "group", "batch", "replicate")]
q <- q[duplicated(q)==F,]
e <- merge(x = e, y = q, all.x = T)

g <- ggplot()+
  facet_wrap(~paste0(treatment, " (", gsub(pattern = "n", replacement = '', 
                                          x = replicate), ")"), ncol = 3, scales = "free")+
  geom_violin(data = e, aes(x = as.factor(dose), y = yhat, linetype = batch), 
              fill = NA, col = "black", linetype = "dashed")+
  geom_sina(data = o$x, aes(x = as.factor(dose), y = sv, col = batch), 
            col = "red", size = 0.3)+
  theme_bw(base_size = 10)+
  theme(legend.position = "none")+
  theme(strip.text.x = element_text(margin = margin(0.02,0,0.02,0, "cm")))+
  xlab(label = "dose")+
  scale_y_continuous(name = "s", breaks = scales::pretty_breaks(3))+
  scale_color_manual(values = c("orange", "steelblue"))
g
```



# Session Info

```{r}
sessionInfo()
```

